# Generated by Django 5.1.4 on 2024-12-08 09:03

import django.db.models.deletion
import localflavor.pk.models
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_location_post_code_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.pk.models.PKStateField(default='Punjab', max_length=5),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=users.utils.get_user_directory),
        ),
    ]
