# Generated by Django 5.1.4 on 2024-12-12 17:24

import django.db.models.deletion
import home.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_location_state_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(choices=[('bmw', 'BMW'), ('mercedes', 'mercedes'), ('toyota', 'Toyota'), ('suzuki', 'SUZUKI')], default='BMW', max_length=60)),
                ('model', models.CharField(max_length=4)),
                ('vin', models.CharField(max_length=130)),
                ('color', models.CharField(default='white', max_length=50)),
                ('description', models.TextField()),
                ('milage', models.CharField(max_length=50)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('auto', 'AUTOMATIC')], max_length=50)),
                ('pic', models.ImageField(upload_to=home.utils.get_listings_directory)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
