# Generated by Django 5.1.4 on 2024-12-15 07:13

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_listing101'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing101',
            name='location',
            field=localflavor.us.models.USStateField(default='California', max_length=2),
        ),
    ]
